### ISSUE TITLE
Client wont login when trying to save access token

### ISSUE THREAD

**Issue by mjeshurun** [heruoxin/Pushbullet-NW#1]
Client stuck on login after pasting access code and pressing save.
OS X 10.10.1
Pushbullet-NW Version 0.1.9 (35.0.1916.157) (1916.157)

**Comment by heruoxin** [comment]
Sorry, It's a bug. Try the [0.2.0](https://github.com/heruoxin/Pushbullet-NW/blob/release-download/Pushbullet-NW.app.zip?raw=true)?

**Comment by mjeshurun** [comment]
0.2.0 Works! Thanks :)

**Comment by mjeshurun** [comment]
0.2.0 client logs in and syncs old pushes, but will not receive new pushs.

**Comment by heruoxin** [comment]
You can restart the app and try again. If it still can not receive new pushs, press cmd+i and paste text from console to here.
